name: daily csv action
on:
  push:
    branches:
      - main
jobs:
  csv-generator:
    runs-on: ubuntu-latest 
    env: 
      CI_COMMIT_MESSAGE: daily csv generated
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: install requirements
      run: pip3 install -r requirements.txt
    - name: run script
      run: ./run.sh
    - name: directory contents
      run: ls -al
    - name: push repo
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add *
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
        
