name: test-action
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: install requirements
      run: pip3 install -r requirements.txt
    - name: run script
      run: ./run.sh
        
